it_company_task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path(
        "",
        include(
            "task_manager.urls",
            namespace="task_manager"
        )
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

task_manager/urls.py
from django.urls import path
from task_manager.views import (
    index,
    WorkerListView,
    WorkerDetailView,
    WorkerCreateView,
    WorkerUpdateView,
    WorkerAccountsUpdateView,
    WorkerDeleteView,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    TaskTypeListView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,

)

urlpatterns = [
    path("", index, name="index"),
    path(
        "workers/",
        WorkerListView.as_view(),
        name="worker-list"
    ),
    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path(
        "workers/create/",
        WorkerCreateView.as_view(),
        name="worker-create"
    ),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker-update"
    ),
    path(
        "workers/accounts/<int:pk>/update/",
        WorkerAccountsUpdateView.as_view(),
        name="worker-accounts-update"
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker-delete"
    ),
    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list"
    ),
    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="positions-create"
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="positions-update"
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="positions-delete"
    ),
    path(
        "task-types/",
        TaskTypeListView.as_view(),
        name="task-type-list"
    ),
    path(
        "task-types/create/",
        TaskTypeCreateView.as_view(),
        name="task-types-create"
    ),
    path(
        "task-types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-types-update"
    ),
    path(
        "task-types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-types-delete"
    ),
    path(
        "projects/<int:project_id>/tasks/",
        ProjectDetailView.as_view(),
        name="task-list"
    ),
    path(
        "projects/<int:project_id>/tasks/<int:pk>/",
        TaskDetailView.as_view(),
        name="task-detail"
    ),
    path(
        "projects/<int:project_id>/tasks/create/",
        TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "projects/<int:project_id>/tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"),

    path(
        "projects/<int:project_id>/tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "projects/",
        ProjectListView.as_view(),
        name="project-list"
    ),
    path(
        "projects/<int:project_id>/",
        ProjectDetailView.as_view(),
        name="project-detail"
    ),
    path(
        "projects/create/",
        ProjectCreateView.as_view(),
        name="project-create"
    ),
    path(
        "projects/<int:project_id>/update/",
        ProjectUpdateView.as_view(),
        name="project-update"
    ),
    path(
        "projects/<int:project_id>/delete/",
        ProjectDeleteView.as_view(),
        name="project-delete"
    ),
]

app_name = "task_manager"

task_manager/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from it_company_task_manager import settings


class Position(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self):
        return self.name


class TaskType(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self):
        return self.name


class Worker(AbstractUser):
    position = models.ForeignKey(
        Position,
        on_delete=models.CASCADE,
        null=True,
    )

    class Meta:
        verbose_name = "worker"
        verbose_name_plural = "workers"

    def __str__(self):
        return f"{self.last_name} {self.first_name}"


class Project(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    deadline = models.DateField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    assignees = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="projects"
    )

    def __str__(self):
        return self.name


class Task(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateField(null=False, blank=False)
    is_completed = models.BooleanField(default=False)
    priority = models.CharField(
        max_length=6,
        choices=(
            ("Urgent", "Urgent"),
            ("High", "High"),
            ("Normal", "Normal"),
            ("Low", "Low"),
        ),
        default="Normal",
    )
    task_type = models.ForeignKey(
        TaskType,
        on_delete=models.CASCADE,
        related_name="tasks"
    )
    assignees = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="assignees"
    )
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        related_name="tasks"
    )

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.name

task_manager/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.forms import PasswordInput, DateInput
from django.contrib.auth.forms import UserCreationForm

from task_manager.models import Worker, Task, Project


class WorkerCreateForm(forms.ModelForm):
    password = forms.CharField(widget=PasswordInput())

    class Meta(UserCreationForm.Meta):
        model = Worker
        fields = [
            "username",
            "password",
            "first_name",
            "last_name",
            "position"
        ]


class WorkerUpdateForm(forms.ModelForm):

    class Meta(UserCreationForm.Meta):
        model = Worker
        fields = ("last_name", "position",)


class WorkerAccountsUpdateForm(forms.ModelForm):

    class Meta(UserCreationForm.Meta):
        model = Worker
        fields = ("username", "email", "position", "first_name", "last_name",)


class TaskForm(forms.ModelForm):
    deadline = forms.DateField(widget=DateInput(attrs={'type': 'date'}))

    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Task
        fields = [
            "name",
            "description",
            "deadline",
            "is_completed",
            "priority",
            "task_type",
            "assignees"
        ]


class TaskSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by task name"}),
    )


class ProjectSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search"}),
    )


class ProjectForm(forms.ModelForm):

    deadline = forms.DateField(widget=DateInput(attrs={'type': 'date'}))

    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Project
        fields = [
            "name",
            "description",
            "deadline",
            "is_completed",
            "assignees"
        ]

task_manager/views.py
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.shortcuts import render
from django.urls import reverse_lazy


from task_manager.forms import (
    WorkerUpdateForm,
    WorkerCreateForm,
    TaskForm,
    TaskSearchForm,
    WorkerAccountsUpdateForm,
    ProjectSearchForm,
    ProjectForm,
)
from task_manager.models import (
    Worker,
    Task,
    TaskType,
    Position, Project
)


def index(request):
    num_workers = Worker.objects.count()

    context = {
        "num_workers": num_workers,
    }

    return render(request, "task_manager/index.html", context=context)


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    queryset = Worker.objects.select_related("position")


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker
    queryset = Worker.objects.prefetch_related("position")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        worker = self.object
        project_id = self.request.GET.get("project_id")
        is_completed = self.request.GET.get("is_completed")

        tasks = Task.objects.filter(assignees=worker)

        if project_id:
            tasks = tasks.filter(project_id=project_id)

        if is_completed is not None:
            is_completed = is_completed.lower() == "true"
            tasks = tasks.filter(is_completed=is_completed)

        context["tasks"] = tasks
        return context


class WorkerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Worker
    form_class = WorkerCreateForm
    success_url = reverse_lazy("task_manager:worker-list")


class WorkerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = WorkerUpdateForm
    success_url = reverse_lazy("task_manager:worker-list")


class WorkerAccountsUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = WorkerAccountsUpdateForm
    success_url = reverse_lazy("task_manager:index")


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    template_name = "task_manager/worker_confirm_delete.html"
    success_url = reverse_lazy("task_manager:worker-list")


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task
    queryset = Task.objects.prefetch_related("assignees")


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm

    def get_success_url(self):
        project_id = self.kwargs['project_id']
        return reverse("task_manager:project-detail", kwargs={"project_id": project_id})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['project_id'] = self.kwargs['project_id']
        return context

    def form_valid(self, form):
        project_id = self.kwargs['project_id']
        project = get_object_or_404(Project, id=project_id)
        form.instance.project = project
        return super().form_valid(form)


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['project_id'] = self.kwargs['project_id']
        return context

    def get_success_url(self):
        task = self.get_object()
        return reverse_lazy(
            "task_manager:project-detail",
            kwargs={"project_id": task.project_id}
        )


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    template_name = "task_manager/task_confirm_delete.html"

    def get_success_url(self):
        task = self.get_object()
        return reverse_lazy(
            "task_manager:project-detail",
            kwargs={"project_id": task.project_id}
        )


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("task_manager:position-list")
    template_name = "task_manager/position_form.html"


class PositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("task_manager:position-list")
    template_name = "task_manager/position_form.html"


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    template_name = "task_manager/position_confirm_delete.html"
    success_url = reverse_lazy("task_manager:position-list")


class TaskTypeListView(LoginRequiredMixin, generic.ListView):
    model = TaskType
    template_name = "task_manager/task_type_list.html"


class TaskTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = TaskType
    fields = "__all__"
    success_url = reverse_lazy("task_manager:task-type-list")
    template_name = "task_manager/task_type_form.html"


class TaskTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = TaskType
    fields = "__all__"
    success_url = reverse_lazy("task_manager:task-type-list")
    template_name = "task_manager/task_type_form.html"


class TaskTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = TaskType
    template_name = "task_manager/task-type_confirm_delete.html"
    success_url = reverse_lazy("task_manager:task-type-list")


class ProjectMixin:
    @staticmethod
    def get_project(project_id):
        queryset = ProjectMixin.get_project_queryset()
        return get_object_or_404(queryset, id=project_id)

    @staticmethod
    def get_project_queryset():
        return Project.objects.all()


class ProjectListView(LoginRequiredMixin, generic.ListView):
    model = Project
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = ProjectSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = ProjectMixin.get_project_queryset()
        is_completed = self.request.GET.get("is_completed")
        form = ProjectSearchForm(self.request.GET)

        if is_completed:
            is_completed = is_completed.lower() == "true"
            queryset = queryset.filter(is_completed=is_completed)
        if form.is_valid():
            queryset = queryset.filter(name__icontains=form.cleaned_data["name"])

        return queryset


class ProjectDetailView(LoginRequiredMixin, generic.DetailView):
    model = Project
    template_name = "task_manager/project_detail.html"
    context_object_name = "project"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = TaskSearchForm(self.request.GET)
        context["filtered_tasks"] = self.get_filtered_tasks().prefetch_related('task_type')
        context["task_types"] = TaskType.objects.all()
        return context

    def get_object(self, queryset=None):
        project_id = int(self.kwargs.get("project_id"))
        queryset = ProjectMixin.get_project_queryset()
        return get_object_or_404(queryset, id=project_id)

    def get_filtered_tasks(self):
        project_id = int(self.kwargs.get("project_id"))
        project = ProjectMixin.get_project(project_id)
        tasks = project.tasks.all()
        form = TaskSearchForm(self.request.GET)
        if form.is_valid():
            name = form.cleaned_data["name"]
            tasks = tasks.filter(name__icontains=name)
        priority = self.request.GET.get("priority")
        if priority:
            tasks = tasks.filter(priority=priority)
        task_type_id = self.request.GET.get("task_type_id")
        if task_type_id:
            tasks = tasks.filter(task_type_id=task_type_id)

        is_completed = self.request.GET.get("is_completed")
        if is_completed is not None:
            is_completed = is_completed.lower() == "true"
            tasks = tasks.filter(is_completed=is_completed)
        return tasks.distinct()


class ProjectCreateView(LoginRequiredMixin, generic.CreateView):
    model = Project
    form_class = ProjectForm
    success_url = reverse_lazy("task_manager:project-list")


class ProjectUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Project
    form_class = ProjectForm
    success_url = reverse_lazy("task_manager:project-list")

    def get_object(self, queryset=None):
        project_id = self.kwargs.get("project_id")
        return ProjectMixin.get_project(project_id)


class ProjectDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Project
    template_name = "task_manager/project_confirm_delete.html"
    success_url = reverse_lazy("task_manager:project-list")

    def get_object(self, queryset=None):
        project_id = self.kwargs.get("project_id")
        return ProjectMixin.get_project(project_id)

templates/task_manager/position_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Delete Position</h1>

<p>Are you sure you want to delete the position {{ position }}?</p>
<p><i>All Worker with this position will be also deleted!</i></p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete" class="btn btn-danger">

</form>

{% endblock %}

templates/task_manager/position_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Position List
    <a href="{% url 'task_manager:positions-create' %}"
      type="submit"
         class="btn btn-success"
        style="height: 40px">ADD POSITION
      </a>
  </h1>
  <div class="col-12 col-lg-12">
    <div class="card card-table">
       <div class="card-header">
           <div class="tools dropdown"> <span class="icon mdi mdi-download"></span><a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown"><span class="icon mdi mdi-more-vert"></span></a>
             <div class="dropdown-menu" role="menu"><a class="dropdown-item" href="#">Action</a><a class="dropdown-item" href="#">Another action</a><a class="dropdown-item" href="#">Something else here</a>
               <div class="dropdown-divider"></div><a class="dropdown-item" href="#">Separated link</a>
               </div>
             </div>
         <div class="title">Positions</div>
       </div>
          <div class="card-body table-responsive">
              {% if position_list %}
                <table  class="table table-striped table-borderless">
                  <thead>
                    <tr>
                      <th style="width:40%;">Name</th>

                      <th style="width:15%; padding-left: 45px">UPDATE</th>
                      <th style="width:15%; padding-left: 45px">DELETE</th>
                    </tr>
                  </thead>
                  {% for position in position_list %}
                    <tbody class="no-border-x">
                      <tr>
                        <td>{{ position.name }}
                        </td>
                        <td>
                          <a type="button" class="btn btn-warning" href="{% url "task_manager:positions-update" pk=position.id %}">UPDATE</a>
                        </td>
                        <td>
                          <a type="button" class="btn btn-danger" href="{% url "task_manager:positions-delete" pk=position.id %}">DELETE</a>
                        </td>
                      </tr>
                    </tbody>
                  {% endfor %}
                </table>
          </div>
       </div>

    </div>
    {% block pagination %}
       {% include "includes/pagination.html" %}
    {% endblock %}

    {% else %}
      <p> The are no position in company</p>
    {% endif %}
{% endblock %}

templates/task_manager/project_detail.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <section class="section section-lg bg-gray-50 py-5" id="pricing">
      <div class="container">
        <div class="row justify-content-between">
          <div class="col-12 col-lg-4" style="margin-left: 80px">
            <p>
              <a href="{% url 'task_manager:project-update' project_id=project.id %}?next={{request.path}}"
              type="submit"
              class="btn btn-warning">UPDATE
            </a>
            <a href="{% url 'task_manager:project-delete' project_id=project.id %}"
              type="submit"
              class="btn btn-danger">DELETE
            </a></p>
            <h2>
              Project: {{ project.name }} <span>
              </span>
            </h2>
            <p>Deadline: {{ project.deadline }}</p>
            <p>
              Is completed: {{ project.is_completed }}
            </p><a href="{% url 'task_manager:task-create' project_id=project.pk %}?next={{request.path}}"
              type="submit"
              class="btn btn-success">ADD TASK
            </a>
          </div>
          <div class="col-12 col-lg-4 " style="margin-right: 80px">
            {% if project.assignees %}
               <br>
                <p style="color: #0a53be">
                  Team: {{ project.assignees.count }} assignee{{ project.assignees.count|pluralize }}
                </p>
                {% for worker in project.assignees.all %}
                    <p>
                      {{ worker.position }} - {{ worker.last_name }} {{ worker.first_name }}
                    </p>
                {% endfor %}
            {% else %}
              <p>No team</p>
            {% endif %}
          </div>
        </div>
      </div>
    </section>
  <br>
    <section class="section section-lg bg-gray-50 py-5" id="pricing">
        <div>
          <h5 class="text-uppercase text-primary letter-spacing-3">
            Project: {{ project.name }}
          </h5>
          <p class="lead text-muted mb-4 ">
            Description: {{ project.description }} </p>
      </div>
      <div>
      <div>
      <form style="padding-left: 10px" action="{% url 'task_manager:project-detail' project_id=project.id %}" method="get">      <h4>Filter</h4>
          <div class="d-flex">
            <div class="form-group">
              <label for="priority">Priority:</label>
              <select name="priority" id="priority" class="form-control">
                <option value="" {% if not request.GET.priority %}selected{% endif %}>All</option>
                <option value="Low" {% if request.GET.priority == "Low" %}selected{% endif %}>Low</option>
                <option value="Urgent" {% if request.GET.priority == "Urgent" %}selected{% endif %}>Urgent</option>
                <option value="High" {% if request.GET.priority == "High" %}selected{% endif %}>High</option>
                <option value="Normal" {% if request.GET.priority == "Normal" %}selected{% endif %}>Normal</option>
              </select>
            </div>

            <div class="form-group">
                <label for="task_type">Type</label>
                <select name="task_type_id" id="task_type" class="form-control">
                    <option value="" {% if not request.GET.task_type_id %}selected{% endif %}>All</option>
                    {% for task_type in task_types %}
                        <option value="{{ task_type.pk }}" {% if request.GET.task_type_id|stringformat:"s" == task_type.pk|stringformat:"s" %}selected{% endif %}>{{ task_type.name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group">
              <label for="is_completed">Is Completed</label>
              <select name="is_completed" id="is_completed" class="form-control">
                  <option value="" {% if not request.GET.is_completed %}selected{% endif %}>All</option>
                  <option value="true" {% if request.GET.is_completed == "true" %}selected{% endif %}>Yes</option>
                  <option value="false" {% if request.GET.is_completed == "false" %}selected{% endif %}>No</option>
              </select>
            </div>
          </div>
          <button type="submit" class="btn btn-primary">Apply Filter</button>
        </form>
        <br>
        <form style="padding-left: 10px" action="{% url 'task_manager:project-detail' project_id=project.id %}" method="get" class="form-inline">
          <div class="input-group">
            {{ search_form|crispy }}
            <div class="input-group-append">
              <button class="btn btn-secondary" type="submit">🔎</button>
            </div>
          </div>
        </form>
        <div style="padding-left: 10px; padding-right: 10px" class="col-12 col-lg-12">
          <div class="card card-table">
             <div class="card-header">
                 <div class="tools dropdown"> <span class="icon mdi mdi-download"></span><a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown"><span class="icon mdi mdi-more-vert"></span></a>
                   <div class="dropdown-menu" role="menu"><a class="dropdown-item" href="#">Action</a><a class="dropdown-item" href="#">Another action</a><a class="dropdown-item" href="#">Something else here</a>
                     <div class="dropdown-divider"></div><a class="dropdown-item" href="#">Separated link</a>
                     </div>
                   </div>
               <div class="title">Purchases</div>
             </div>
                <div class="card-body table-responsive">
                    {% if filtered_tasks %}
                      <table class="table table-striped table-borderless">
                        <thead>
                          <tr>
                            <th>Task Type</th>
                            <th style="padding-left: 40px">Task</th>
                            <th style="padding-left: 40px">Deadline</th>
                            <th>Is completed</th>
                            <th>Priority</th>
                            <th style="padding-left: 40px">UPDATE</th>
                            <th style="padding-left: 40px">DELETE</th>
                          </tr>
                        </thead>
                        {% for task in filtered_tasks %}
                          <tbody class="no-border-x">
                            <tr>
                              <td>{{ task.task_type }}</td>
                              <td>
                                <a style="color: #0a6f4d; text-decoration: underline" href="{% url 'task_manager:task-detail' project_id=project.id pk=task.id %}">
                                  {{ task.name }}
                                </a>
                              </td>
                              <td>{{ task.deadline }}</td>
                              {% if task.is_completed is True %}
                                <td class="text-success">{{ task.is_completed }}</td>
                              {% else %}
                                <td class="text-danger">{{ task.is_completed }}</td>
                              {% endif %}
                              <td>{{ task.priority }}</td>
                              <td>
                                  <a type="button"
                                     class="btn btn-warning"
                                     href="{% url 'task_manager:task-update' project_id=project.id pk=task.id %}">
                                    UPDATE
                                  </a>
                              </td>
                              <td>
                                <a type="button"
                                   class="btn btn-danger"
                                   href="{% url 'task_manager:task-delete' project_id=project.id pk=task.id %}">
                                  DELETE
                                </a>
                              </td>
                            </tr>
                          </tbody>
                        {% endfor %}
                      </table>
                </div>
             </div>
        </div>
            {% block pagination %}
              {% include "includes/pagination.html" %}
            {% endblock %}
                  {% else %}
                    <p>The are no tas in project.</p>
                  {% endif %}
    </section>



{% endblock %}

templates/task_manager/task_type_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update, Create" }} Task type</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

  <input type="submit" value="Submit" class="btn btn-success">
  </form>
{% endblock %}

templates/task_manager/worker_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Worker List
    <a href="{% url 'task_manager:worker-create' %}"
      type="submit"
         class="btn btn-success"
        style="height: 40px">ADD WORKER
      </a>
  </h1>
  <div class="col-12 col-lg-12">
    <div class="card card-table">
       <div class="card-header">
           <div class="tools dropdown"> <span class="icon mdi mdi-download"></span><a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown"><span class="icon mdi mdi-more-vert"></span></a>
             <div class="dropdown-menu" role="menu"><a class="dropdown-item" href="#">Action</a><a class="dropdown-item" href="#">Another action</a><a class="dropdown-item" href="#">Something else here</a>
               <div class="dropdown-divider"></div><a class="dropdown-item" href="#">Separated link</a>
               </div>
             </div>
         <div class="title">Workers</div>
       </div>
          <div class="card-body table-responsive">
              {% if worker_list %}
                <table  class="table table-striped table-borderless">
                  <thead>
                    <tr>
                      <th style="width:20%;">Position </th>
                      <th style="width:15%;">Username </th>
                      <th style="width:30%; padding-left: 90px">Name</th>
                      <th style="width:15%; padding-left: 50px">UPDATE</th>
                      <th style="width:15%; padding-left: 50px">DELETE</th>
                    </tr>
                  </thead>
                  {% for worker in worker_list %}
                    <tbody class="no-border-x">
                      <tr>
                        <td>{{ worker.position }}
                        </td>
                        <td ><a href="#">{{ worker.username }}</a></td>
                        <td>{{ worker.last_name }} {{ worker.first_name }}</td>
                        <td>
                          <a type="button" class="btn btn-warning" href="{% url "task_manager:worker-update" pk=worker.id %}">UPDATE</a>
                        </td>
                        <td>
                          <a type="button" class="btn btn-danger" href="{% url "task_manager:worker-delete" pk=worker.id %}">DELETE</a>
                        </td>
                      </tr>
                    </tbody>
                  {% endfor %}
                </table>
          </div>
       </div>

    </div>
        {% block pagination %}
          {% include "includes/pagination.html" %}
        {% endblock %}

    {% else %}
       <p>  The are no worker in company</p>
    {% endif %}

{% endblock %}